service: slack-widget-proxy

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  
  environment: 
      token: ${opt:token}
      bucket: ${opt:bucket}
      region: ${opt:region}
  
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 's3:PutObject'
      Resource:
        Fn::Join:
          - ''
          - - 'arn:aws:s3:::'
            - ${opt:bucket}
            - '/*'
    - Effect: 'Allow'
      Action:
        - 's3:GetObject'
      Resource:
        Fn::Join:
          - ''
          - - 'arn:aws:s3:::'
            - ${opt:bucket}
            - '/*'

functions:      
  viewProfile:
    handler: src/handlers/profileView.handleViewProfile
    events:
        - http:
            path: profile/view/{id}
            method: get
            cors: true
            request:
              parameters:
                paths:
                  id: true
                  
  listProfiles:
    handler: src/handlers/listProfiles.handleListProfiles
    events:
        - http:
            path: profile/list
            method: get
            cors: true